<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../classes/Cesta.php';
require_once __DIR__ . '/../config/helpers.php';
$titulo='Minha Cesta'; require_once __DIR__ . '/header.php';
$cesta=new Cesta(Database::getConnection());$itens=$cesta->listarPorUsuario(usuarioId());$resumo=$cesta->resumoPorUsuario(usuarioId());$mensagem='';
if(($_GET['remover']??'')!==''){ $cesta->removerProduto(usuarioId(),(int)$_GET['remover']); header('Location: cesta.php'); exit; }
if(isset($_GET['limpar'])){$cesta->limpar(usuarioId());header('Location: cesta.php');exit;}
?>
<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4"><div><h1 class="h2 fw-bold">Minha Cesta</h1><p class="text-secondary mb-0">Cada produto aparece apenas uma vez, conforme solicitado no trabalho.</p></div><a href="produtos.php" class="btn btn-outline-primary">Adicionar produtos</a></div>
<div class="row g-4"><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Produto</th><th>Fornecedor</th><th>Preço</th><th></th></tr></thead><tbody><?php foreach($itens as $i):?><tr><td><div class="fw-semibold"><?=e($i['nome'])?></div><small class="text-secondary"><?=e($i['descricao']?:'Sem descrição')?></small></td><td><?=e($i['fornecedor_nome'])?></td><td><?=preco($i['preco'])?></td><td class="text-end"><a href="?remover=<?=$i['id']?>" class="btn btn-sm btn-outline-danger">Remover</a></td></tr><?php endforeach;?><?php if(!$itens):?><tr><td colspan="4" class="text-center py-5"><div class="fs-5 fw-semibold">Sua cesta está vazia</div><div class="text-secondary mb-3">Selecione produtos na página de Produtos.</div><a href="produtos.php" class="btn btn-primary">Ver produtos</a></td></tr><?php endif;?></tbody></table></div></div><?php if($itens):?><div class="card-footer bg-white text-end"><a href="?limpar=1" class="btn btn-outline-danger btn-sm" onclick="return confirm('Limpar toda a cesta?')">Limpar cesta</a></div><?php endif;?></div></div><div class="col-lg-4"><div class="card border-0 shadow-sm summary-card"><div class="card-body p-4"><h5 class="fw-bold mb-4">Resumo</h5><div class="d-flex justify-content-between mb-3"><span class="text-secondary">Produtos selecionados</span><strong><?=$resumo['quantidade']?></strong></div><hr><div class="d-flex justify-content-between align-items-end"><span class="text-secondary">Valor total</span><span class="fs-3 fw-bold"><?=preco($resumo['total'])?></span></div></div></div></div></div>
<?php require_once __DIR__ . '/footer.php'; ?>
